
services:
  postgres:
    image: postgres:16-alpine
    container_name: dispatch_postgres
    restart: always
    environment:
      POSTGRES_DB: dispatch_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    container_name: dispatch_mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: dispatch_redis
    restart: always
    ports:
      - '5356:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  mongodata:
  redisdata: